#!/bin/bash

echo getting unicorn pid
# pid=$(ps aux | grep 'unicorn master' | grep -v '(old)' | grep -v grep | awk '{print $2}')
pid=$(cat /www/number_guru/tmp/unicorn.pid)

echo hupping unicorn process $pid
kill -HUP $pid
# sleep 1
# kill $pid